services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Evolution\EvolutionDefinitionInterface:
            tags:
                - { name: evolution.type.definition }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Validator\Constraints\EvolutionTypeValidator:
        arguments:
            $definitions: !tagged_locator { tag: evolution.type.definition, default_index_method: 'getType' }
